# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(default='unknown', max_length=255)),
                ('email', models.EmailField(default='unknown', max_length=265)),
            ],
        ),
    ]
